In [1]:
import os
import json
import pandas as pd
import psycopg2

In [4]:
#Aggregated insurance folder data

path= "C:/Users/Jonathan Simon/Desktop/New folder/PhonePe project/pulse/data/aggregated/insurance/country/india/state/"
agg_insurance_list= os.listdir(path)

columns= {'States':[], 'Years':[], 'Quarter':[], 'Transaction_type':[], 'Transaction_count':[], 'Transaction_amount':[]}

for state in agg_insurance_list:
    current_states= path+state+"/"
    agg_year_list= os.listdir(current_states)

    for year in agg_year_list:
        current_year= current_states+year+"/"
        agg_file_list= os.listdir(current_year)

        for file in agg_file_list:
            current_file= current_year+file
            data =open(current_file,"r")

            A= json.load(data)

            for i in A['data']['transactionData']:
                name= i['name']
                count= i['paymentInstruments'][0]['count']
                amount= i['paymentInstruments'][0]['amount']
                columns['Transaction_type'].append(name)
                columns['Transaction_count'].append(count)
                columns['Transaction_amount'].append(amount)
                columns['States'].append(state)
                columns['Years'].append(year)
                columns['Quarter'].append(int(file.strip('.json')))

aggregated_insurance= pd.DataFrame(columns)

aggregated_insurance['States']=aggregated_insurance['States'].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
aggregated_insurance['States']=aggregated_insurance['States'].str.replace('-',' ')
aggregated_insurance['States']=aggregated_insurance['States'].str.title()
aggregated_insurance['States']=aggregated_insurance['States'].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [5]:
aggregated_insurance['States'].unique()

array(['Andaman & Nicobar', 'Andhra Pradesh', 'Arunachal Pradesh',
       'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh',
       'Dadra and Nagar Haveli and Daman and Diu', 'Delhi', 'Goa',
       'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu & Kashmir',
       'Jharkhand', 'Karnataka', 'Kerala', 'Ladakh', 'Lakshadweep',
       'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
       'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan',
       'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh',
       'Uttarakhand', 'West Bengal'], dtype=object)

In [6]:
#Aggregated transcation folder data

path1="C:/Users/Jonathan Simon/Desktop/New folder/PhonePe project/pulse/data/aggregated/transaction/country/india/state/"
agg_tran_list= os.listdir(path1)

columns2={'States':[], 'Years':[], 'Quarter':[], 'Transaction_type':[], 'Transaction_count':[], 'Transaction_amount':[]}

for state in agg_tran_list:
    current_states= path1+state+"/"
    agg_year_list= os.listdir(current_states)

    for year in agg_year_list:
        current_year= current_states+year+"/"
        agg_file_list= os.listdir(current_year)

        for file in agg_file_list:
            current_file= current_year+file
            data =open(current_file,"r")

            B= json.load(data)

            for i in B['data']['transactionData']:
                name= i['name']
                count= i['paymentInstruments'][0]['count']
                amount= i['paymentInstruments'][0]['amount']
                columns2['Transaction_type'].append(name)
                columns2['Transaction_count'].append(count)
                columns2['Transaction_amount'].append(amount)
                columns2['States'].append(state)
                columns2['Years'].append(year)
                columns2['Quarter'].append(int(file.strip('.json')))

aggregated_transaction= pd.DataFrame(columns2)

aggregated_transaction['States']=aggregated_transaction['States'].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
aggregated_transaction['States']=aggregated_transaction['States'].str.replace('-',' ')
aggregated_transaction['States']=aggregated_transaction['States'].str.title()
aggregated_transaction['States']=aggregated_transaction['States'].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [7]:
# aggregated user folder data

path2= "C:/Users/Jonathan Simon/Desktop/New folder/PhonePe project/pulse/data/aggregated/user/country/india/state/"
agg_user_list= os.listdir(path2)

columns3= {'States':[], 'Years':[], 'Quarter':[], 'Brand':[], 'Transaction_count':[], 'Percentage':[]}

for state in agg_user_list:
    current_states= path2+state+"/"
    agg_year_list= os.listdir(current_states)

    for year in agg_year_list:
        current_year= current_states+year+"/"
        agg_file_list= os.listdir(current_year)

        for file in agg_file_list:
            current_file= current_year+file
            data= open(current_file,"r")

            C= json.load(data)

            try:
                for i in C['data']['usersByDevice']:
                    brand= i['brand']
                    count =i['count']
                    percentage= i["percentage"]
                    columns3['Brand'].append(brand)
                    columns3['Transaction_count'].append(count)
                    columns3['Percentage'].append(percentage)
                    columns3['States'].append(state)
                    columns3['Years'].append(year)
                    columns3['Quarter'].append(int(file.strip('.json')))

            except:
                pass

aggregated_users= pd.DataFrame(columns3)

aggregated_users['States']=aggregated_users['States'].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
aggregated_users['States']=aggregated_users['States'].str.replace('-',' ')
aggregated_users['States']=aggregated_users['States'].str.title()
aggregated_users['States']=aggregated_users['States'].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [8]:
#map insurance folder data

path3= "C:/Users/Jonathan Simon/Desktop/New folder/PhonePe project/pulse/data/map/insurance/hover/country/india/state/"
map_insurance_list= os.listdir(path3)

columns4= {'States':[], 'Years':[], 'Quarter':[], 'Districts':[], 'Transaction_count':[], 'Transaction_amount':[]}

for state in map_insurance_list:
    current_states= path3+state+"/"
    agg_year_list= os.listdir(current_states)

    for year in agg_year_list:
        current_year= current_states+year+"/"
        agg_file_list= os.listdir(current_year)

        for file in agg_file_list:
            current_file= current_year+file
            data= open(current_file,"r")

            D= json.load(data)

            for i in D['data']['hoverDataList']:
                    name= i['name']
                    count =i['metric'][0]['count']
                    amount= i['metric'][0]['amount']
                    columns4['Districts'].append(name)
                    columns4['Transaction_count'].append(count)
                    columns4['Transaction_amount'].append(amount)
                    columns4['States'].append(state)
                    columns4['Years'].append(year)
                    columns4['Quarter'].append(int(file.strip('.json')))

map_insurance= pd.DataFrame(columns4)

map_insurance['States']=map_insurance['States'].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
map_insurance['States']=map_insurance['States'].str.replace('-',' ')
map_insurance['States']=map_insurance['States'].str.title()
map_insurance['States']=map_insurance['States'].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [9]:
# map transaction folder data

path4= "C:/Users/Jonathan Simon/Desktop/New folder/PhonePe project/pulse/data/map/transaction/hover/country/india/state/"
map_tran_list= os.listdir(path4)

columns5= {'States':[], 'Years':[], 'Quarter':[], 'Districts':[], 'Transaction_count':[], 'Transaction_amount':[]}

for state in map_tran_list:
    current_states= path4+state+"/"
    agg_year_list= os.listdir(current_states)

    for year in agg_year_list:
        current_year= current_states+year+"/"
        agg_file_list= os.listdir(current_year)

        for file in agg_file_list:
            current_file= current_year+file
            data= open(current_file,"r")

            E= json.load(data)

            for i in E['data']['hoverDataList']:
                    name= i['name']
                    count =i['metric'][0]['count']
                    amount= i['metric'][0]['amount']
                    columns5['Districts'].append(name)
                    columns5['Transaction_count'].append(count)
                    columns5['Transaction_amount'].append(amount)
                    columns5['States'].append(state)
                    columns5['Years'].append(year)
                    columns5['Quarter'].append(int(file.strip('.json')))

map_transaction= pd.DataFrame(columns5)

map_transaction['States']=map_transaction['States'].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
map_transaction['States']=map_transaction['States'].str.replace('-',' ')
map_transaction['States']=map_transaction['States'].str.title()
map_transaction['States']=map_transaction['States'].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [10]:
#map user folder data

path5= "C:/Users/Jonathan Simon/Desktop/New folder/PhonePe project/pulse/data/map/user/hover/country/india/state/"
map_user_list = os.listdir(path5)

columns6= {'States':[], 'Years':[], 'Quarter':[], 'Districts':[], 'RegisteredUsers':[], 'AppOpens':[]}

for state in map_user_list:
    current_states= path5+state+"/"
    agg_year_list= os.listdir(current_states)

    for year in agg_year_list:
        current_year= current_states+year+"/"
        agg_file_list= os.listdir(current_year)

        for file in agg_file_list:
            current_file= current_year+file
            data= open(current_file,"r")

            F= json.load(data)

            for i in F['data']['hoverData'].items():
                district= i[0]
                registeredUsers =i[1]['registeredUsers']
                appOpens= i[1]['appOpens']
                columns6['Districts'].append(district)
                columns6['RegisteredUsers'].append(registeredUsers)
                columns6['AppOpens'].append(appOpens)
                columns6['States'].append(state)
                columns6['Years'].append(year)
                columns6['Quarter'].append(int(file.strip('.json')))

map_users= pd.DataFrame(columns6)

map_users['States']=map_users['States'].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
map_users['States']=map_users['States'].str.replace('-',' ')
map_users['States']=map_users['States'].str.title()
map_users['States']=map_users['States'].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [11]:
#top insurance folder data

path6= "C:/Users/Jonathan Simon/Desktop/New folder/PhonePe project/pulse/data/top/insurance/country/india/state/"
top_insurance_list= os.listdir(path6)

columns7= {'States':[], 'Years':[], 'Quarter':[], 'Pincodes':[], 'Transaction_count':[], 'Transaction_amount':[]}

for state in top_insurance_list:
    current_states= path6+state+"/"
    agg_year_list= os.listdir(current_states)

    for year in agg_year_list:
        current_year= current_states+year+"/"
        agg_file_list= os.listdir(current_year)

        for file in agg_file_list:
            current_file= current_year+file
            data= open(current_file,"r")

            G= json.load(data)

            for i in G['data']['pincodes']:
                entityname= i['entityName']
                count =i['metric']['count']
                amount= i['metric']['amount']
                columns7['Pincodes'].append(entityname)
                columns7['Transaction_count'].append(count)
                columns7['Transaction_amount'].append(amount)
                columns7['States'].append(state)
                columns7['Years'].append(year)
                columns7['Quarter'].append(int(file.strip('.json')))

top_insurance= pd.DataFrame(columns7)

top_insurance['States']=top_insurance['States'].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
top_insurance['States']=top_insurance['States'].str.replace('-',' ')
top_insurance['States']=top_insurance['States'].str.title()
top_insurance['States']=top_insurance['States'].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [12]:
#top transaction folder data

path7= "C:/Users/Jonathan Simon/Desktop/New folder/PhonePe project/pulse/data/top/transaction/country/india/state/"
top_transaction_list= os.listdir(path7)

columns8= {'States':[], 'Years':[], 'Quarter':[], 'Pincodes':[], 'Transaction_count':[], 'Transaction_amount':[]}

for state in top_transaction_list:
    current_states= path7+state+"/"
    agg_year_list= os.listdir(current_states)

    for year in agg_year_list:
        current_year= current_states+year+"/"
        agg_file_list= os.listdir(current_year)

        for file in agg_file_list:
            current_file= current_year+file
            data= open(current_file,"r")

            H= json.load(data)

            for i in H['data']['pincodes']:
                entityname= i['entityName']
                count =i['metric']['count']
                amount= i['metric']['amount']
                columns8['Pincodes'].append(entityname)
                columns8['Transaction_count'].append(count)
                columns8['Transaction_amount'].append(amount)
                columns8['States'].append(state)
                columns8['Years'].append(year)
                columns8['Quarter'].append(int(file.strip('.json')))

top_transaction= pd.DataFrame(columns8)

top_transaction['States']=top_transaction['States'].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
top_transaction['States']=top_transaction['States'].str.replace('-',' ')
top_transaction['States']=top_transaction['States'].str.title()
top_transaction['States']=top_transaction['States'].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [15]:
#top users folder data

path8= "C:/Users/Jonathan Simon/Desktop/New folder/PhonePe project/pulse/data/top/user/country/india/state/"
top_users_list= os.listdir(path8)

columns9= {'States':[], 'Years':[], 'Quarter':[], 'Pincodes':[], 'Registered_users':[]}

for state in top_users_list:
    current_states= path8+state+"/"
    agg_year_list= os.listdir(current_states)

    for year in agg_year_list:
        current_year= current_states+year+"/"
        agg_file_list= os.listdir(current_year)

        for file in agg_file_list:
            current_file= current_year+file
            data= open(current_file,"r")

            I= json.load(data)

            for i in I['data']['pincodes']:
                entityname= i['name']
                registeredusers =i['registeredUsers']
                columns9['Pincodes'].append(entityname)
                columns9['Registered_users'].append(registeredusers)
                columns9['States'].append(state)
                columns9['Years'].append(year)
                columns9['Quarter'].append(int(file.strip('.json')))

top_users= pd.DataFrame(columns9)

top_users['States']=top_users['States'].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
top_users['States']=top_users['States'].str.replace('-',' ')
top_users['States']=top_users['States'].str.title()
top_users['States']=top_users['States'].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [17]:
#table creation in SQL
#sql CONNECTION

mydb= psycopg2.connect(host= 'localhost',
                        user= 'postgres',
                        password= 'Joshie@0910',
                        database= 'phonepe_data',
                        port= '5432')
cursor= mydb.cursor()

#aggregated insurance table

create_query1= '''CREATE TABLE if not exists aggregated_insurance(States varchar(200),
                                                    Years int,
                                                    Quarter int,
                                                    Transaction_type varchar(200),
                                                    Transaction_count bigint,
                                                    Transaction_amount bigint)'''
cursor.execute(create_query1)
mydb.commit()

insert_query1= '''INSERT INTO aggregated_insurance(States, Years, Quarter, Transaction_type, Transaction_count, Transaction_amount)
                                                            
                                                        values(%s,%s,%s,%s,%s,%s)'''

data= aggregated_insurance.values.tolist()
cursor.executemany(insert_query1,data)
mydb.commit()

#aggregated transaction table

create_query2= '''CREATE TABLE if not exists aggregated_transaction(States varchar(200),
                                                    Years int,
                                                    Quarter int,
                                                    Transaction_type varchar(200),
                                                    Transaction_count bigint,
                                                    Transaction_amount bigint)'''
cursor.execute(create_query2)
mydb.commit()

insert_query2= '''INSERT INTO aggregated_transaction(States, Years, Quarter, Transaction_type, Transaction_count, Transaction_amount)
                                                            
                                                        values(%s,%s,%s,%s,%s,%s)'''

data= aggregated_transaction.values.tolist()
cursor.executemany(insert_query2,data)
mydb.commit()

#aggregated users table

create_query3= '''CREATE TABLE if not exists aggregated_users(States varchar(200),
                                                    Years int,
                                                    Quarter int,
                                                    Brand varchar(200),
                                                    Transaction_count bigint,
                                                    Percentage float)'''
cursor.execute(create_query3)
mydb.commit()

insert_query3= '''INSERT INTO aggregated_users(States, Years, Quarter, Brand, Transaction_count, Percentage)
                                                            
                                                        values(%s,%s,%s,%s,%s,%s)'''

data= aggregated_users.values.tolist()
cursor.executemany(insert_query3,data)
mydb.commit()

#map insurance table

create_query4= '''CREATE TABLE if not exists map_insurance(States varchar(200),
                                                    Years int,
                                                    Quarter int,
                                                    Districts varchar(200),
                                                    Transaction_count bigint,
                                                    Transaction_amount bigint)'''
cursor.execute(create_query4)
mydb.commit()

insert_query4= '''INSERT INTO map_insurance(States, Years, Quarter, Districts, Transaction_count, Transaction_amount)
                                                            
                                                        values(%s,%s,%s,%s,%s,%s)'''

data= map_insurance.values.tolist()
cursor.executemany(insert_query4,data)
mydb.commit()

#map transaction table

create_query5= '''CREATE TABLE if not exists map_transaction(States varchar(200),
                                                    Years int,
                                                    Quarter int,
                                                    Districts varchar(200),
                                                    Transaction_count bigint,
                                                    Transaction_amount bigint)'''
cursor.execute(create_query5)
mydb.commit()

insert_query5= '''INSERT INTO map_transaction(States, Years, Quarter, Districts, Transaction_count, Transaction_amount)
                                                            
                                                        values(%s,%s,%s,%s,%s,%s)'''

data= map_transaction.values.tolist()
cursor.executemany(insert_query5,data)
mydb.commit()

#map users table

create_query6= '''CREATE TABLE if not exists map_users(States varchar(200),
                                                    Years int,
                                                    Quarter int,
                                                    Districts varchar(200),
                                                    RegisteredUsers bigint,
                                                    AppOpens bigint)'''
cursor.execute(create_query6)
mydb.commit()

insert_query6= '''INSERT INTO map_users(States, Years, Quarter, Districts, RegisteredUsers, AppOpens)
                                                            
                                                        values(%s,%s,%s,%s,%s,%s)'''

data= map_users.values.tolist()
cursor.executemany(insert_query6,data)
mydb.commit()

#top insurance table

create_query7= '''CREATE TABLE if not exists top_insurance(States varchar(200),
                                                    Years int,
                                                    Quarter int,
                                                    Pincodes varchar(200),
                                                    Transaction_count bigint,
                                                    Transaction_amount bigint)'''
cursor.execute(create_query7)
mydb.commit()

insert_query7= '''INSERT INTO top_insurance(States, Years, Quarter, Pincodes, Transaction_count, Transaction_amount)
                                                            
                                                        values(%s,%s,%s,%s,%s,%s)'''

data= top_insurance.values.tolist()
cursor.executemany(insert_query7,data)
mydb.commit()

#top transaction table

create_query8= '''CREATE TABLE if not exists top_transaction(States varchar(200),
                                                    Years int,
                                                    Quarter int,
                                                    Pincodes varchar(200),
                                                    Transaction_count bigint,
                                                    Transaction_amount bigint)'''
cursor.execute(create_query8)
mydb.commit()

insert_query8= '''INSERT INTO top_transaction(States, Years, Quarter, Pincodes, Transaction_count, Transaction_amount)
                                                            
                                                        values(%s,%s,%s,%s,%s,%s)'''

data= top_transaction.values.tolist()
cursor.executemany(insert_query8,data)
mydb.commit()

#top user table

create_query9= '''CREATE TABLE if not exists top_users(States varchar(200),
                                                    Years int,
                                                    Quarter int,
                                                    Pincodes varchar(200),
                                                    Registered_users bigint)'''
cursor.execute(create_query9)
mydb.commit()

insert_query9= '''INSERT INTO top_users(States, Years, Quarter, Pincodes, Registered_users)
                                                            
                                                        values(%s,%s,%s,%s,%s)'''

data= top_users.values.tolist()
cursor.executemany(insert_query9,data)
mydb.commit()